### ISSUE TITLE
Can't run on RTX4090

### ISSUE THREAD

**Issue by CellNw** [openai/consistency_models_cifar10#1]
I got it to run successfully on my RTX3070 laptop, but when I was on 4 x RTX4090 I couldn't get it to run successfully.
My System Environment: OS:ubuntu 22.04, Cuda:12.2，Python:3.9.16
command:` python -m jcm.main --config configs/cifar10_k_ve.py --workdir cifar10-kve-score-loss --mode train --num_gpus 4`
Error message:
```
I0628 18:07:53.872016 140170550791040 xla_bridge.py:455] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
INFO - xla_bridge.py - 2023-06-28 18:07:53,872 - Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I0628 18:07:53.874046 140170550791040 xla_bridge.py:455] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
INFO - xla_bridge.py - 2023-06-28 18:07:53,874 - Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0628 18:07:53.874833 140170550791040 xla_bridge.py:455] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
INFO - xla_bridge.py - 2023-06-28 18:07:53,874 - Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2023-06-28 18:07:55.163739: W external/xla/xla/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-06-28 18:07:55.163784: W external/xla/xla/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2023-06-28 18:07:55.182018: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:540] failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
2023-06-28 18:07:55.182062: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:545] error log buffer (63 bytes): error   : Binary format for key='0', ident='' is not recognize
2023-06-28 18:07:55.182180: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2432] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid.
Traceback (most recent call last):
  File "/home/mlt01/szl/consistency_models_cifar10/jcm/main.py", line 86, in <module>
    app.run(main)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/mlt01/szl/consistency_models_cifar10/jcm/main.py", line 66, in main
    train.train(FLAGS.config, FLAGS.workdir)
  File "/home/mlt01/szl/consistency_models_cifar10/jcm/train.py", line 57, in train
    rng = hk.PRNGSequence(config.seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/haiku/_src/base.py", line 862, in __init__
    key_or_seed = jax.random.PRNGKey(key_or_seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 734, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 746, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 751, in random_seed_impl_base
    return seed(seeds)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 980, in threefry_seed
    return _threefry_seed(seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/pjit.py", line 208, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/pjit.py", line 155, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/pjit.py", line 1108, in _pjit_call_impl
    return compiled.unsafe_call(*args)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 1346, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mlt01/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mlt01/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mlt01/szl/consistency_models_cifar10/jcm/main.py", line 86, in <module>
    app.run(main)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/mlt01/szl/consistency_models_cifar10/jcm/main.py", line 66, in main
    train.train(FLAGS.config, FLAGS.workdir)
  File "/home/mlt01/szl/consistency_models_cifar10/jcm/train.py", line 57, in train
    rng = hk.PRNGSequence(config.seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/haiku/_src/base.py", line 862, in __init__
    key_or_seed = jax.random.PRNGKey(key_or_seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 734, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 746, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 751, in random_seed_impl_base
    return seed(seeds)
  File "/home/mlt01/.pyenv/versions/consistency/lib/python3.9/site-packages/jax/_src/prng.py", line 980, in threefry_seed
    return _threefry_seed(seed)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.func.launch' failed: Failed to load PTX text as a module: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid.
```

Is there any way to fix it?

**Comment by CellNw** [comment]
I know what the problem is, don't use command `apt install nvidia-cuda-tookit` to install nvidia cuda toolkit, but go to the nvidia website and download cuda for installation.
