### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by LI-Yiquan** [openai/consistency_models_cifar10#7]
I got the following bug.

"Traceback (most recent call last):
  File "/home/yiquan/.conda/envs/consistency_models_cifar10/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yiquan/.conda/envs/consistency_models_cifar10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yiquan/consistency_models_cifar10/jcm/main.py", line 86, in <module>
    app.run(main)
  File "/home/yiquan/.conda/envs/consistency_models_cifar10/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/yiquan/.conda/envs/consistency_models_cifar10/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/yiquan/consistency_models_cifar10/jcm/main.py", line 66, in main
    train.train(FLAGS.config, FLAGS.workdir)
  File "/home/yiquan/consistency_models_cifar10/jcm/train.py", line 60, in train
    score_model, init_model_state, initial_params = mutils.init_model(next(rng), config)
  File "/home/yiquan/consistency_models_cifar10/jcm/models/utils.py", line 103, in init_model
    init_model_state, initial_params = variables.pop("params")
ValueError: too many values to unpack (expected 2)"

when I run.

"python -m jcm.main --config configs/cifar10_k_ve.py --workdir cifar10-kve-score-loss --mode train"

How can I solve this?

**Comment by LI-Yiquan** [comment]
Solved by downgrade flax package.
